### ISSUE TITLE
Error implementing lib

### ISSUE THREAD

**Issue by cristianofmc** [donv/capybara-screenshot-diff#63] opened 2023-01-27 14:38 UTC
I'm trying to implement this capybara screenshot diff, but I'm getting an error

I added these lines on gem file
```
gem 'capybara-screenshot-diff'
gem 'oily_png', platform: :ruby
```
I rode the command
`bundle`

In my testes steps file  I tried it:

```
require 'capybara/screenshot/diff'


test 'my useful feature' do
  visit '/'
  include Capybara::Screenshot::Diff
  screenshot 'welcome_index'
end
```

but I received and error:
`undefined method 'screenshot' for #......(NoMethodError)`

so I changed to:

```
require 'capybara/screenshot/diff'
include Capybara::Screenshot::Diff

test 'my useful feature' do
  visit '/'
  screenshot 'welcome_index'
end
```
but I received and error:
`undefined method 'setup' for Object:Class (NoMethodError)`

I've tried reinstalling and redoing the process, but I always get these same types of errors, how can I fix it?

**Comment by pftg** [comment] 2023-01-27 15:10
Hey, @cristianofmc thanks for interest into the project. I’ll check it today. But looks like you added tests outside of the Testcase class Could you use try like

```ruby
class ExploreFeature < ActiveSupport::TestCase
  include Capybara::Screenshot::Diff
  test ‘feature’ do
   screenshot ‘page’
  end
end 
```

**Comment by pftg** [comment] 2023-02-09 18:37
@cristianofmc could not reproduce your problem if I use as I shared https://github.com/donv/capybara-screenshot-diff/issues/63#issuecomment-1406635762. Could you confirm that it works for you?

**Comment by pftg** [comment] 2023-02-28 11:52
@cristianofmc please check my response. For now I'm closing it, if needed we can reopen it later.

**Closed by pftg** 2023-02-28 11:52 UTC
